### ISSUE TITLE
想了解下 自定义vue 节点或者 自定义path节点应该怎么处理

### ISSUE THREAD

**Issue by 6313504** [lloydzhou/vue-x6#1]

**Comment by lloydzhou** [comment]
1. 这个库只是使用组件的方式将之前x6以API操作画布的方式换成使用vue组件的方式：

```
    <Node id="100" label="path" :x="400" :y="200" :width="80" :height="80" shape="path" path="M 0 5 10 0 C 20 0 20 20 10 20 L 0 15 Z" :attrs="{body: {fill: '#efdbff', stroke: '#9254de'}}" />
```

2. 至于vue组件，这里也有一个demo：前面注册组件之类的都是一样的逻辑。只是将官方demo里面的addNode换成写一个vue组件而已
```
  graph.addNode({
     shape: "custom-vue-node",
     x: 100,
     y: 60,
   });

--> 

<Node shape="custom-vue-node" :x="400" :y="100" />
```

![image](https://user-images.githubusercontent.com/1826685/226083733-9247f26d-08c7-4d9b-8b66-93778d88854b.png)

**Comment by 6313504** [comment]
谢谢哦 上面2种demo的写法正是我需要的 也看到npmjs的更新了 之前看源码 Node 里面的 shape 是rect 我还以为别的需要重新定义的

**Comment by lloydzhou** [comment]
npm更新主要是移除了一个没有使用到的变量，（当然也更新了一下readme，增加了你提到的两种demo）
![image](https://user-images.githubusercontent.com/1826685/226154221-6e6f3309-8aa0-4bb7-9314-d3e8ccf6ca9e.png)

**Comment by lloydzhou** [comment]
你提到源码里面的应该是这一行：
```
export const Node = ElementOf("Node", createCell.bind(null, X6Node.create, 'rect'))
```
这里可能确实需要改一下。这里bind传进去的shape参数，好像没有使用到...

**Comment by lloydzhou** [comment]
1. 修复了createCell传进去的shape值未使用到的问题。
2. 修复了patchProp只更新有变化的值，导致更新节点属性丢失bug
