### ISSUE TITLE
刚才尝试了  node 嵌套 node  好像不能像 demo里面 那样 拖动父节点 一起拖动 

### ISSUE THREAD

**Issue by 6313504** [lloydzhou/vue-x6#2]
刚才尝试了  node 嵌套 node  好像不能像 demo里面 那样 拖动父节点 一起拖动 https://x6.antv.antgroup.com/zh/examples/node/group/#embedding-nodes

**Comment by lloydzhou** [comment]
https://github.com/lloydzhou/vue-x6/blob/master/src/App.vue#L41
![image](https://user-images.githubusercontent.com/1826685/226161756-a197e12e-a8db-4505-a714-949b221db396.png)

项目中的demo，拖动node1, node3是能拖动的
![image](https://user-images.githubusercontent.com/1826685/226161776-e1f24832-b5ad-476f-aa7b-7500bea5c687.png)

**Comment by 6313504** [comment]
好的 谢谢
