### ISSUE TITLE
不支持 v-for

### ISSUE THREAD

**Issue by 6313504** [lloydzhou/vue-x6#3]
<template v-for="node in nodes">
      <Node :id="node.id" parent="102" :label="node.label" :height="node.height" :width="node.width" :x="node.x"
        :y="node.y" />
    </template>

或者 

      <Node :id="node.id" parent="102" :label="node.label" :height="node.height" :width="node.width" :x="node.x"
        :y="node.y" v-for="node in nodes" />

都不支持

const nodes = [
  {
    id: '1-1',
    label: '1-1',
    height: 10,
    width: 10,
    x: 10,
    y: 10
  }
]

**Comment by lloydzhou** [comment]
确实，v-for会动态创建一个`Fragment`把这几个children包裹起来。这个地方确实没有处理好，这两天会做一下兼容

**Comment by lloydzhou** [comment]
![image](https://user-images.githubusercontent.com/1826685/226320363-2e931576-8eb6-4bce-8e42-b49dbeb336f1.png)

![image](https://user-images.githubusercontent.com/1826685/226320400-1702354a-8982-4a6b-bd14-65029feedf41.png)

**Comment by lloydzhou** [comment]
昨天下午试了试，通过v-for增加一个Fragment是可以的。但是动态的增加或者移除多个Fragment的时候，会导致内部陷入死循环。。。
这里还需要重新调整：
1. 正确处理这种Fragment带来的层级关系
2. 或者，在processChildren函数将元素拉平，不要这种层级？
